maths = int(input("Enter maths mark =>"))
sci = int(input("Enter sci mark =>"))
hindi = int(input("Enter hindi mark =>"))
print("total =",maths+sci+hindi)
print("sub =",maths-sci-hindi)
print("mul =",maths*sci*hindi)
print("div =",maths/sci/hindi)